-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 16:15:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema edugo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edugo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edugo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema announcements
-- -----------------------------------------------------
USE `edugo` ;

-- -----------------------------------------------------
-- Table `edugo`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(10) NOT NULL,
  `create_on` DATETIME NOT NULL,
  `update_on` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `role` ENUM('admin', 'user', 'provider') NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`admins` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `status` ENUM('Active', 'Inactive') NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_admins_accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`providers` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(50) NOT NULL,
  `url` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `status` ENUM('Active', 'Inactive') NOT NULL,
  `verify` ENUM('Y', 'N') NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`provider_id`),
  INDEX `fk_providers_accounts1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_providers_accounts1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`posts` (
  `posts_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `url` VARCHAR(50) NULL,
  `attach_file` LONGBLOB NULL,
  `posts_type` ENUM('Announce', 'Subject') NOT NULL,
  `publish_date` DATETIME NULL DEFAULT NULL,
  `close_date` DATETIME NULL DEFAULT NULL,
  `provider_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`posts_id`),
  INDEX `fk_posts_providers1_idx` (`provider_id` ASC) VISIBLE,
  INDEX `fk_posts_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_posts_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `edugo`.`providers` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edugo`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edugo`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`comments` (
  `comments_id` INT NOT NULL AUTO_INCREMENT,
  `comments_text` VARCHAR(500) NOT NULL,
  `comments_file` LONGBLOB NULL,
  `comments_type` ENUM('Announce', 'Subject') NOT NULL,
  `publish_date` DATETIME NULL DEFAULT NULL,
  `posts_id` INT NOT NULL,
  `user_id` INT NULL,
  `provider_id` INT NULL,
  PRIMARY KEY (`comments_id`),
  INDEX `fk_comments_posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comments_providers1_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `edugo`.`posts` (`posts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edugo`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `edugo`.`providers` (`provider_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edugo`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo`.`categories` (
  `category_id` INT NOT NULL,
  `category_name` VARCHAR(45) NOT NULL,
  `category_type` ENUM('Announce', 'Subject') NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_categories_posts1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `edugo`.`posts` (`posts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
