-- MySQL Script generated by MySQL Workbench
-- Mon Oct 14 12:40:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema edugo_v3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edugo_v3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edugo_v3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `edugo_v3` ;

-- -----------------------------------------------------
-- Table `edugo_v3`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `phone_number` VARCHAR(10) NOT NULL,
  `create_on` DATETIME NOT NULL,
  `update_on` DATETIME NOT NULL,
  `last_login` DATETIME NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `role` ENUM('admin', 'user', 'provider') NOT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`admins` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `status` ENUM('Active', 'Inactive') NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`admin_id`),
  INDEX `fk_admin_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_admin_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo_v3`.`accounts` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`tags` (
  `tag_id` INT NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo_v3`.`accounts` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `attach_file` LONGBLOB NULL DEFAULT NULL,
  `tag_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `tag_id` (`tag_id` ASC) VISIBLE,
  INDEX `fk_commu_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `commu_ibfk_1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `edugo_v3`.`tags` (`tag_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_commu_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `edugo_v3`.`users` (`user_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`providers` (
  `provider_id` INT NOT NULL AUTO_INCREMENT,
  `provider_name` VARCHAR(50) NOT NULL,
  `url` VARCHAR(50) NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `status` ENUM('Active', 'Inactive') NOT NULL,
  `verify` ENUM('Y', 'N') NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`provider_id`),
  INDEX `fk_provider_account1_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_provider_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `edugo_v3`.`accounts` (`account_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`subjectments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`subjectments` (
  `subjectment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_text` VARCHAR(500) NOT NULL,
  `comment_file` LONGBLOB NULL DEFAULT NULL,
  `commu_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`subjectment_id`),
  INDEX `commu_id` (`commu_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_commu_comment_provider1_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `commu_comment_ibfk_1`
    FOREIGN KEY (`commu_id`)
    REFERENCES `edugo_v3`.`subjects` (`subject_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `commu_comment_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `edugo_v3`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_commu_comment_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `edugo_v3`.`providers` (`provider_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`posts` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `url` VARCHAR(100) NULL DEFAULT NULL,
  `attach_file` LONGBLOB NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  INDEX `fk_post_provider1_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `edugo_v3`.`providers` (`provider_id`),
  CONSTRAINT `post_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `edugo_v3`.`categories` (`category_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `edugo_v3`.`postments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edugo_v3`.`postments` (
  `postment_id` INT NOT NULL AUTO_INCREMENT,
  `comment_text` VARCHAR(500) NULL DEFAULT NULL,
  `comment_file` LONGBLOB NULL DEFAULT NULL,
  `post_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`postment_id`),
  INDEX `post_id` (`post_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `fk_post_comment_provider1_idx` (`provider_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_comment_provider1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `edugo_v3`.`providers` (`provider_id`),
  CONSTRAINT `post_comment_ibfk_1`
    FOREIGN KEY (`post_id`)
    REFERENCES `edugo_v3`.`posts` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `post_comment_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `edugo_v3`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
